### ISSUE TITLE
BUG: Operator cleanup removes entire namesace

### ISSUE THREAD

**Issue by psaxton** [sai3010/Typesense-Kubernetes-Operator#11]
**Describe the bug**
When the operator is cleaned up, it removes the entire namespace including resources which are not managed by the operator.

**To Reproduce**

1) Apply operator to namespace with existing resources
2) Remove operator from namespace

**Expected behavior**
It should be expected that the operator would clean up the resources it manages: Config Map, Stateful Set, Persistent Volume Claims, Persistent Volumes, Service, Headless Service, etc.

All resources not managed by the operator should be left untouched.

**Please complete the following information:**
 - Kubernetes version
     - 1.28.5 (eks)
     - 1.32.0 (minikube)
 - Typesense version
     - 0.25.0
     - 0.25.2
 - Cloud provider or self-managed?
     - AWS (EKS)
     - self-managed localhost (minikube)

**Additional context**
This bug could potentially cause serious damage when applied to a working environment.

**Comment by sai3010** [comment]
@psaxton Thanks for pointing it out, will release a fix soon.

**Comment by sai3010** [comment]
This is Fixed.
