### ISSUE TITLE
Possibility to use Kubernetes secrets instead of clear password

### ISSUE THREAD

**Issue by fharper** [sai3010/Typesense-Kubernetes-Operator#15]
**Is your feature request related to a problem? Please describe.**
If using GitOps to deploy this operator, the password in the YAML file will be clearly visible.

**Describe the solution you'd like**
Being able to use Kubernetes Secrets in addition of string for the password.

**Describe alternatives you've considered**
There is none that I can think of.

**Additional context**
I agree that the indexed data for public sites are not critical, still I wouldn't like to have a bad actor screw up my indexes as they can easily retrieve the admin password (API key). It's another story for private information. With that said, even if the `gitops` repository is private, still not a good practice to have the password committed in it, when it could be in a secret.

**Comment by pbtrudel** [comment]
+1 on this feature!
Since everything we deploy in Kubernetes is in Git, have the password in clear text is not great. 
This limitation is my only concern right now with using this operator.  Would it be possible to implement this?

**Comment by sai3010** [comment]
@pbtrudel @fharper Sure I will take it up. Thank you!

**Comment by sai3010** [comment]
I am closing this as it is resolved in release 2.1. @pbtrudel @fharper
