### ISSUE TITLE
Add Healthchecks to StatefulSet for Improved Traffic Management in Typesense Service

### ISSUE THREAD

**Issue by sharkyak** [sai3010/Typesense-Kubernetes-Operator#2]
Currently, the Typesense service continues to route traffic to nodes even when they're in a failed state. 
This results in inconsistent performance and can lead to service interruptions. 
To tackle this issue, it's crucial to add health checks to the StatefulSet so that nodes in failed states are not included in the traffic pool.

**Comment by sai3010** [comment]
Thanks. It is resolved in version 1.2.
