### ISSUE TITLE
BUG Node list not dynamically updated after pod recreation

### ISSUE THREAD

**Issue by kebulaAntonio** [sai3010/Typesense-Kubernetes-Operator#21]
Hi, I have deployed a Typesense cluster on EKS with 3 replicas. When a pod dies and is recreated, it gets a new IP address, but the node list in the Typesense cluster is not updated automatically, causing connectivity issues between the nodes. The new pod appears to attempt to communicate with the other nodes using its new IP, but the cluster still retains the old IP addresses. This leads to connectivity failures, and the cluster cannot function correctly after a pod is recreated.

Here is a log from the failing pod:
I20240930 10:01:12.758893   139 node.cpp:1579] node default_group:172.31.0.188:8107:8108 term 3 start pre_vote
W20240930 10:01:12.758957   139 node.cpp:1589] node default_group:172.31.0.188:8107:8108 can't do pre_vote as it is not in 172.31.2.11:8107:8108,172.31.34.27:8107:8108,172.31.30.43:8107:8108.

The node list contains old IP addresses (e.g., 172.31.2.11, 172.31.34.27, 172.31.30.43), but the newly created pod has the IP 172.31.0.188. The cluster should dynamically update its node list when a pod is recreated, but this does not seem to happen, causing the pod to be excluded from cluster operations.

Steps to Reproduce:
-     Deploy a Typesense cluster on EKS with 3 replicas.
-     Kill one of the pods to force it to be recreated.
-     Observe the logs and notice that the recreated pod gets a new IP address, but the old IP address is still retained in the cluster configuration.
-     Check for connectivity issues between the nodes in the cluster.
Expected Behavior: The node list in the Typesense cluster should dynamically update when a pod is recreated and its IP changes.
Actual Behavior: The node list is not updated automatically, causing connectivity failures between the nodes when one of them is recreated with a new IP.

**Comment by sai3010** [comment]
This is fixed and will be available in the upcoming release. Please upgrade to te latest version.
