### ISSUE TITLE
BUG : Typesense operator crashes with error: from app import resource_create_count_success, resource_delete_count_success, resource_update_count_success ModuleNotFoundError: No module named 'app'

### ISSUE THREAD

**Issue by sonoresama** [sai3010/Typesense-Kubernetes-Operator#30]
**Describe the bug**
The operator pod keeps crashing with error:
from app import resource_create_count_success, resource_delete_count_success, resource_update_count_success
ModuleNotFoundError: No module named 'app'

**To Reproduce**
Apply operator:
kubectl apply -f deploy/operator.yaml

**Expected behavior**
The operator should run and be marked as READY by Kubernetes

**Please complete the following information:**
 - Kubernetes version
 v1.30.0
 - Typesense version
 
 - Cloud provider or self-managed?
Minikube v1.33.1

**Additional context**
I tried downgraded to typesense operator v2.3 but it failed.

**Comment by sai3010** [comment]
Hi,
@sonoresama, please downgrade to 2.2, I will fix this and keep you posted.
